### ISSUE TITLE
meant to crash when API limit is hit?

### ISSUE THREAD

**Issue by fbegue** [ahmed-zubair-1998/Saveddit#2]
On an account with 900+ saved posts, I receive this after loading:
```
scheduler.production.min.js:14 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at saved.js:160
    at Array.filter (<anonymous>)
    at saved (saved.js:159)
    at redux.js:459
    at y (redux.js:213)
    at Search.jsx:17
```
... and so on. Is this by design or would you rather just stop after the limit is reached and warn the user?

Love the site btw! much cleaner then the alternative `https://redditmanager.com/app`

**Comment by ahmed-zubair-1998** [comment]
This is not due to the limits on API. The API just returns the first 900 or so posts and thats all we can access. 

This error seems to have occurred because some value had empty string possibly the subreddit name. However, subreddit name should always be present as it is coming from Reddit APIs.

If you have more details on how to reproduce please let me know.
