### ISSUE TITLE
Issue syncing my Reddit account to this tool

### ISSUE THREAD

**Issue by 999mile** [ahmed-zubair-1998/Saveddit#8]
Hello i just found your tool, and im having an issue connecting to it. Once i put my account login, and press accept, it loads for a little bit and then takes me back to the login page for Saveddit where it. Can you fix?

**Comment by ahmed-zubair-1998** [comment]
I would need more details from your end to figure out the root cause as I am unable to reproduce the issue. Can you check your network tab and console tab from developers tools while running the website? If you see any error please share them here.

**Comment by ahmed-zubair-1998** [comment]
This issue happens when cookies are not enbaled. Either you have blocked third party cookies or you are using incognito window where they are blocked by default. This website use cookies for authentication purposes. If they are blocked you wont login

**Comment by kyle0r** [comment]
FWIW - here are the adjustments required to get things (Saveddit) working with restrictive Firefox settings + uBlock origin. Firefox version 119. I would assume comparable steps would be required on other browsers with restrictive settings.

**uBlock:** allow 3rd-party frames (if needed) for ahmed-zubair-1998.github.io

**Firefox:** disable "protections" - this might not be required if the following exceptions exist.

![image](https://github.com/ahmed-zubair-1998/Saveddit/assets/517822/ce545255-dcf0-41f7-9107-574ca95f626a)

and... create two "cookies and site data" exceptions - these was definitely required, especially the https://saveddit-sdzm.onrender.com one.

![image](https://github.com/ahmed-zubair-1998/Saveddit/assets/517822/52c28eae-ff2a-4e6b-9393-0ca7364d4051)

----------

Thanks @ahmed-zubair-1998 for your useful tool and opening the source code for others to learn/follow/contribute.  
IDEA: Might be worth putting a warning somewhere on your app about the cookies and 3rd party frame requirements?

Perhaps this issue is resolved?

**Comment by ahmed-zubair-1998** [comment]
@kyle0r Thank you for adding detailed descriptions on the issue and the workaround.

As part of #10, I have moved to token based authentication instead of cookie based authentication. This would allow the website to run without needing to enable third party cookies.
